### ISSUE TITLE
No title casing & validation at server side

### ISSUE THREAD

**Issue by Pankajtanwarbanna** [Ananto30/golpo13-v2#7]
Hi @Ananto30 ,

Our discussion at comment section in your Dev.to post brought me here. I was just going through your code. It's a really great job. 

I would not say an issue, but implementing title casing on fields like Name of the user at server side before saving it to the database is a good practice to have. Like i entered my name while registering as "PanKaj tanWar" , it will be saved like this only. Which looks bad, as per my opinion. Whatever the name user enter, save it as "Pankaj Tanwar".  

Apart from this, having a custom validation at Password for the security, at Name for having a valid length, at email etc. 

What are your thoughts ?

Pankaj

**Comment by Ananto30** [comment]
Nice catch! For now, we actually do NOT register users in the system, so there's no way to input names. But we register users from Gmail/Google account, you can find the name before `@` is registered in the system.
The plan is to actually introduce `displayName` field. User can edit that in the edit profile button. So this can be a todo!

**Comment by Pankajtanwarbanna** [comment]
Oh.. Sorry for spamming :) Any plans to have registration feature in near future?

**Comment by Ananto30** [comment]
Not in the near future.
The plan is to add more OAuth's like GitHub, Twitter, Facebook, etc.

**Comment by Pankajtanwarbanna** [comment]
Cool. Now, I am looking for interesting TODOs to work on!

**Comment by Ananto30** [comment]
Great! Closing this.
